### ISSUE TITLE
LookML Generation

### ISSUE THREAD

**Issue by fbertsch** [mozilla/lookml-generator#4]
Given a BQ schema, generate a LookML spec.

Once this is done, the LookML generator should also allow a data structure that describes alterations we want to make to the LookML. For example, we may want to hide fields, add new fields, add new parameters to fields, or alter existing parameters.

**Comment by fbertsch** [comment]
Note: This should be standalone in order to easily support Phase 2 of the Looker Deploy (sometime in H2, probably)

**Comment by fbertsch** [comment]
https://docs.google.com/document/d/1-0Krpe8wB3rZjTj9ud2ywP101d-FMZXpx7Cz_KQ-l8w/edit#heading=h.6jphdj6afi37

**Comment by fbertsch** [comment]
Got a rec to use [pylookML](https://pylookml.readthedocs.io/en/latest/eav.html) and [looker_sdk](https://github.com/looker-open-source/sdk-codegen/tree/main/python).

**Comment by relud** [comment]
notes for myself when I start on this:
- schemas can be acquired by either describing or dry-running views. describing views has the downside that the resulting schema may be stale if an underlying table's schema changed since the view was last updated. It may be possible to work around that limitation by ensuring that view deploys are run even when they don't change.

**Comment by fbertsch** [comment]
First: Generate LookML for ping tables, use existing LookML Generation in Looker as a template (using group labels within the explores)

**Comment by fbertsch** [comment]
This was finished.
